### ISSUE TITLE
Não é possível buildar usando a versão `25.x.x` do Electron

### ISSUE THREAD

**Issue by ferreira-tb** [ferreira-tb/ares#274]
Não acredito que devam demorar para resolver esse problema.

```
An unhandled rejection has occurred inside Forge:
Error: Could not detect abi for version 25.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
at Object.getAbi (C:\workspace\ares\node_modules\node-abi\index.js:39:9)
    at get ABI [as ABI] (C:\workspace\ares\node_modules\@electron\rebuild\lib\src\rebuild.js:86:39)
    at get metaData [as metaData] (C:\workspace\ares\node_modules\@electron\rebuild\lib\src\module-rebuilder.js:50:58)
    at ModuleRebuilder.alreadyBuiltByRebuild (C:\workspace\ares\node_modules\@electron\rebuild\lib\src\module-rebuilder.js:55:34)
    at async Rebuilder.rebuildModuleAt (C:\workspace\ares\node_modules\@electron\rebuild\lib\src\rebuild.js:122:28)
    at async Rebuilder.rebuild (C:\workspace\ares\node_modules\@electron\rebuild\lib\src\rebuild.js:112:17)
```

**Comment by ferreira-tb** [comment]
Reinstalar o `electron-forge` foi suficiente.
